language: python
python: 
   - "2.6"
   - "2.7"
install: 
   - "pip install . --use-mirrors"
   - "pip install -r requirements.txt --use-mirrors"
script: nosetests
before_install:
   - sudo apt-get update -qq
   - sudo apt-get install -qq python-dev libyaml-dev libxml2-dev libxslt-dev libsofthsm softhsm opensc libengine-pkcs11-openssl
