sudo: false
language: python
python:
  - 2.7

addons:
  apt:
    packages:
      - libxml2-dev
      - libxslt-dev
      - libsofthsm
      - softhsm
      - opensc
      - libengine-pkcs11-openssl
      - swig
      - xmlsec1

install:
  - pip install pykcs11
  - pip install nose
  - pip install coveralls

script:
  - coverage run --source=xmlsec setup.py nosetests -vv -d

after_success:
  - coveralls
